"""empty message

Revision ID: 09b3e5d3a2f5
Revises: 1308502231c7
Create Date: 2021-01-02 16:38:51.693475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b3e5d3a2f5'
down_revision = '1308502231c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Usertype', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('joined', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_time_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    op.drop_column('user', 'last_time_seen')
    op.drop_column('user', 'joined')
    op.drop_column('user', 'Usertype')
    # ### end Alembic commands ###
