"""empty message

Revision ID: 55b8e45fb3e2
Revises: 09b3e5d3a2f5
Create Date: 2021-01-02 16:43:52.264085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b8e45fb3e2'
down_revision = '09b3e5d3a2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Usertype', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('joined', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_time_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    op.drop_column('user', 'last_time_seen')
    op.drop_column('user', 'joined')
    op.drop_column('user', 'Usertype')
    # ### end Alembic commands ###
