"""empty message

Revision ID: 5fdb58f01661
Revises: 6f0ab1a7eefa
Create Date: 2021-01-02 16:51:30.931423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fdb58f01661'
down_revision = '6f0ab1a7eefa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('usertype', sa.String(length=30), nullable=False))
    op.drop_column('user', 'Usertype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Usertype', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('user', 'usertype')
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
